// Code generated by protoc-gen-go.
// source: chat.proto
// DO NOT EDIT!

/*
Package chat_packet is a generated protocol buffer package.

It is generated from these files:
	chat.proto

It has these top-level messages:
	UserInfo
	ReqLogin
	ResLogin
	ReqUserList
	ResUserList
	ReqSendChat
	NotifyChat
*/
package chat_packet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PacketType int32

const (
	PacketType_CHAT_PACKET_VERSION PacketType = 100
	PacketType_USER_INFO           PacketType = 101
	PacketType_ROOM_INFO           PacketType = 102
	PacketType_REQ_LOGIN           PacketType = 1001
	PacketType_RES_LOGIN           PacketType = 1002
	PacketType_REQ_USER_LIST       PacketType = 1003
	PacketType_RES_USER_LIST       PacketType = 1004
	PacketType_REQ_SEND_CHAT       PacketType = 1005
	PacketType_NOTIFY_CHAT         PacketType = 1006
)

var PacketType_name = map[int32]string{
	100:  "CHAT_PACKET_VERSION",
	101:  "USER_INFO",
	102:  "ROOM_INFO",
	1001: "REQ_LOGIN",
	1002: "RES_LOGIN",
	1003: "REQ_USER_LIST",
	1004: "RES_USER_LIST",
	1005: "REQ_SEND_CHAT",
	1006: "NOTIFY_CHAT",
}
var PacketType_value = map[string]int32{
	"CHAT_PACKET_VERSION": 100,
	"USER_INFO":           101,
	"ROOM_INFO":           102,
	"REQ_LOGIN":           1001,
	"RES_LOGIN":           1002,
	"REQ_USER_LIST":       1003,
	"RES_USER_LIST":       1004,
	"REQ_SEND_CHAT":       1005,
	"NOTIFY_CHAT":         1006,
}

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}
func (x PacketType) String() string {
	return proto.EnumName(PacketType_name, int32(x))
}
func (x *PacketType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PacketType_value, data, "PacketType")
	if err != nil {
		return err
	}
	*x = PacketType(value)
	return nil
}

type Result int32

const (
	Result_OK   Result = 0
	Result_FAIL Result = 1
)

var Result_name = map[int32]string{
	0: "OK",
	1: "FAIL",
}
var Result_value = map[string]int32{
	"OK":   0,
	"FAIL": 1,
}

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}
func (x Result) String() string {
	return proto.EnumName(Result_name, int32(x))
}
func (x *Result) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Result_value, data, "Result")
	if err != nil {
		return err
	}
	*x = Result(value)
	return nil
}

type UserInfo struct {
	Id               *int32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Nickname         *string `protobuf:"bytes,2,req,name=nickname" json:"nickname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}

func (m *UserInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *UserInfo) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

type ReqLogin struct {
	Nickname         *string `protobuf:"bytes,1,req,name=nickname" json:"nickname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}

func (m *ReqLogin) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

type ResLogin struct {
	SenderId         *int32  `protobuf:"varint,1,req,name=sender_id" json:"sender_id,omitempty"`
	Result           *Result `protobuf:"varint,2,opt,name=result,enum=chat_packet.Result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ResLogin) Reset()         { *m = ResLogin{} }
func (m *ResLogin) String() string { return proto.CompactTextString(m) }
func (*ResLogin) ProtoMessage()    {}

func (m *ResLogin) GetSenderId() int32 {
	if m != nil && m.SenderId != nil {
		return *m.SenderId
	}
	return 0
}

func (m *ResLogin) GetResult() Result {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return Result_OK
}

type ReqUserList struct {
	SenderId         *int32 `protobuf:"varint,1,req,name=sender_id" json:"sender_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReqUserList) Reset()         { *m = ReqUserList{} }
func (m *ReqUserList) String() string { return proto.CompactTextString(m) }
func (*ReqUserList) ProtoMessage()    {}

func (m *ReqUserList) GetSenderId() int32 {
	if m != nil && m.SenderId != nil {
		return *m.SenderId
	}
	return 0
}

type ResUserList struct {
	Page             *int32      `protobuf:"varint,1,req,name=page" json:"page,omitempty"`
	PageSize         *int32      `protobuf:"varint,2,req,name=page_size" json:"page_size,omitempty"`
	NumberOfUsers    *int32      `protobuf:"varint,3,req,name=number_of_users" json:"number_of_users,omitempty"`
	UserInfo         []*UserInfo `protobuf:"bytes,4,rep,name=user_info" json:"user_info,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ResUserList) Reset()         { *m = ResUserList{} }
func (m *ResUserList) String() string { return proto.CompactTextString(m) }
func (*ResUserList) ProtoMessage()    {}

func (m *ResUserList) GetPage() int32 {
	if m != nil && m.Page != nil {
		return *m.Page
	}
	return 0
}

func (m *ResUserList) GetPageSize() int32 {
	if m != nil && m.PageSize != nil {
		return *m.PageSize
	}
	return 0
}

func (m *ResUserList) GetNumberOfUsers() int32 {
	if m != nil && m.NumberOfUsers != nil {
		return *m.NumberOfUsers
	}
	return 0
}

func (m *ResUserList) GetUserInfo() []*UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type ReqSendChat struct {
	SenderId         *int32  `protobuf:"varint,1,req,name=sender_id" json:"sender_id,omitempty"`
	Chat             *string `protobuf:"bytes,2,req,name=chat" json:"chat,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReqSendChat) Reset()         { *m = ReqSendChat{} }
func (m *ReqSendChat) String() string { return proto.CompactTextString(m) }
func (*ReqSendChat) ProtoMessage()    {}

func (m *ReqSendChat) GetSenderId() int32 {
	if m != nil && m.SenderId != nil {
		return *m.SenderId
	}
	return 0
}

func (m *ReqSendChat) GetChat() string {
	if m != nil && m.Chat != nil {
		return *m.Chat
	}
	return ""
}

type NotifyChat struct {
	SenderId         *int32  `protobuf:"varint,1,req,name=sender_id" json:"sender_id,omitempty"`
	Chat             *string `protobuf:"bytes,2,req,name=chat" json:"chat,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NotifyChat) Reset()         { *m = NotifyChat{} }
func (m *NotifyChat) String() string { return proto.CompactTextString(m) }
func (*NotifyChat) ProtoMessage()    {}

func (m *NotifyChat) GetSenderId() int32 {
	if m != nil && m.SenderId != nil {
		return *m.SenderId
	}
	return 0
}

func (m *NotifyChat) GetChat() string {
	if m != nil && m.Chat != nil {
		return *m.Chat
	}
	return ""
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "chat_packet.UserInfo")
	proto.RegisterType((*ReqLogin)(nil), "chat_packet.ReqLogin")
	proto.RegisterType((*ResLogin)(nil), "chat_packet.ResLogin")
	proto.RegisterType((*ReqUserList)(nil), "chat_packet.ReqUserList")
	proto.RegisterType((*ResUserList)(nil), "chat_packet.ResUserList")
	proto.RegisterType((*ReqSendChat)(nil), "chat_packet.ReqSendChat")
	proto.RegisterType((*NotifyChat)(nil), "chat_packet.NotifyChat")
	proto.RegisterEnum("chat_packet.PacketType", PacketType_name, PacketType_value)
	proto.RegisterEnum("chat_packet.Result", Result_name, Result_value)
}
